apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rewrite-ingress
  labels:
    app: rewrite-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Enable regular expressions in the path field
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: arch.homework
      http:
        paths:
          # Use a valid RE2 regex to capture the remainder of the path
          - path: /mantogin-crud-user-app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: load-balancer
                port:
                  number: 80
